# Generated by Django 4.1.7 on 2023-03-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("station_id", models.CharField(max_length=50)),
                (
                    "avg_max_temp",
                    models.DecimalField(decimal_places=1, max_digits=6, null=True),
                ),
                (
                    "avg_min_temp",
                    models.DecimalField(decimal_places=1, max_digits=6, null=True),
                ),
                (
                    "total_precipitation",
                    models.DecimalField(decimal_places=1, max_digits=6, null=True),
                ),
            ],
            options={
                "unique_together": {("year", "station_id")},
            },
        ),
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "max_temp",
                    models.DecimalField(decimal_places=1, max_digits=6, null=True),
                ),
                (
                    "min_temp",
                    models.DecimalField(decimal_places=1, max_digits=6, null=True),
                ),
                (
                    "precipitation",
                    models.DecimalField(decimal_places=1, max_digits=6, null=True),
                ),
                ("station_id", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("date", "station_id")},
            },
        ),
    ]
